version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1
configuration: Release
init:
- cmd: git config --global core.autocrlf input
# assembly_info:
#   patch: true
#   file: '**\AssemblyInfo.*'
#   assembly_version: '{version}'
#   assembly_file_version: '{version}'
#   assembly_informational_version: '{version}'
install:
- ps: >-
    $CommitDateTime = [datetime]::Parse($env:APPVEYOR_REPO_COMMIT_TIMESTAMP)

    $env:BuildDate = $CommitDateTime.AddHours(3).ToString('dd.MM.yyyy')

    Write-Host "Building v$env:APPVEYOR_BUILD_VERSION dated $env:BuildDate"
before_build:
- cmd: nuget.exe restore %APPVEYOR_PROJECT_NAME%.sln
build:
  verbosity: minimal
before_package:
- cmd: >-
    echo %APPVEYOR_PROJECT_NAME% v%APPVEYOR_BUILD_VERSION% (%BUILDDATE%) >readme.txt

    echo http://%APPVEYOR_ACCOUNT_NAME%.github.io/%APPVEYOR_PROJECT_NAME% >>readme.txt
after_build:
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-v%APPVEYOR_BUILD_VERSION%.zip readme.txt
